name: Context Auditor (Offline)
on:
  pull_request:
    paths-ignore:
      - '**/*.png'
  push:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r scripts/context_auditor/requirements.txt

      - name: Run context diff
        run: |
          python scripts/context_auditor/diff_context.py               --config .context-auditor/config.yaml               --output .context-logs/${{ github.sha }}.md

      - name: Summarize diff
        run: |
          python scripts/context_auditor/summarize_diff.py               --input .context-logs/${{ github.sha }}.md

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: context-log
          path: .context-logs/${{ github.sha }}.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('.context-logs/${{ github.sha }}.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });